
[project]
name = "gabber-python-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.2"

# Core dependencies needed by both modes
dependencies = [
    "gabber-sdk",
]

[tool.uv.sources]
gabber-sdk = { path = "../" }
